set PROJ_PATH=%CD%
set SRC_NAME=XMODEM50
set SRC_PATH=%PROJ_PATH%\%PROJ_NAME%

set TARGET1_NAME=XM5
set TARGET2_NAME=XM5V2
set TARGET3_NAME=XM5V3

cd /D D:\Users\roman\hobby\hardware_projects\8085\tasm\tasm32

tasm -85 -fFF -l -h -d%TARGET1_NAME% %SRC_PATH%.ASM %PROJ_PATH%\%TARGET1_NAME%.HEX %PROJ_PATH%\%TARGET1_NAME%.LST
tasm -85 -fFF -l -h -d%TARGET2_NAME% %SRC_PATH%.ASM %PROJ_PATH%\%TARGET2_NAME%.HEX %PROJ_PATH%\%TARGET2_NAME%.LST
tasm -85 -fFF -l -h -d%TARGET3_NAME% %SRC_PATH%.ASM %PROJ_PATH%\%TARGET3_NAME%.HEX %PROJ_PATH%\%TARGET3_NAME%.LST

cd /D %PROJ_PATH%

